import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      // Build/Generated directories
      ".next/**",
      "coverage/**",
      "node_modules/**",
      "dist/**",
      "out/**",
      "build/**",

      // Config files
      "**/*.config.*",
      "next-env.d.ts",

      // Infrastructure
      ".{idea,git,cache,output,temp}/**",
      "public/**",
      "dev/**",

      // Database
      "**/drizzle/**",

      // Generated by shadcn/ui
      "src/components/ui/**",
      "src/components/theme/**",
      "src/hooks/use-mobile.ts",
      "src/lib/utils.ts",
    ],
  },
];

export default eslintConfig;
