import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [tsconfigPaths(), react()],
  test: {
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    globals: true,
    coverage: {
      exclude: [
        // Build/Generated directories
        "**/.next/**",
        "**/coverage/**",
        "**/node_modules/**",
        "**/dist/**",

        // Config files
        "**/*.config.*",
        "next-env.d.ts",

        // Infrastructure
        "**/.{idea,git,cache,output,temp}/**",
        "**/public/**",
        "**/dev/**",

        // Database
        "**/drizzle/**",
        "**/src/db/**",

        // Next.js App Router
        "**/src/app/**/page.tsx",
        "**/src/app/layout.tsx",
        "**/middleware.ts",

        // Generated by shadcn/ui
        "**/src/components/ui/**",
        "**/src/components/theme/**",
        "**/src/hooks/use-mobile.ts",
        "**/src/lib/utils.ts",
      ],
    },
  },
});
